import AppKit
import CryptoKit
import SmartClipCore

/// macOS never tells you the clipboard changed, so like every clipboard manager
/// this polls `NSPasteboard.general.changeCount` — an integer compare, a couple
/// of times a second, costing essentially nothing.
final class ClipboardWatcher {
    private let store: HistoryStore
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var lastContent: String?
    private var ignoredContent: String?
    private var lastDigest: String?
    private var ignoredDigest: String?
    private var timer: Timer?

    var isPaused = false
    var onCapture: ((ClipRecord) -> Void)?

    /// Password managers tag what they copy; nspasteboard.org's convention is
    /// that clipboard managers skip anything carrying these markers. That is far
    /// more reliable than trying to recognise a password by looking at it.
    private static let skipMarkers: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    /// Belt and braces for apps that don't set the markers.
    private static let deniedBundleIDs: Set<String> = [
        "com.1password.1password", "com.1password.1password7", "com.agilebits.onepassword7",
        "com.apple.keychainaccess", "com.bitwarden.desktop", "com.lastpass.LastPass",
        "com.dashlane.Dashlane", "in.sinew.Enpass-Desktop",
    ]

    init(store: HistoryStore) {
        self.store = store
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in self?.tick() }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    /// Called before we put something on the clipboard ourselves, so pasting
    /// from history doesn't re-record the same clip.
    func ignore(_ content: String) {
        ignoredContent = content
    }

    func ignore(_ payload: ClipPayload) {
        switch payload {
        case .text(let text): ignoredContent = text
        case .image(let data): ignoredDigest = SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
        case .files(let urls): ignoredContent = urls.map(\.path).joined(separator: "\n")
        }
    }

    private func tick() {
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount
        guard !isPaused else { return }

        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.skipMarkers) else { return }

        let source = sourceApplication()
        if let bundleID = source?.bundleIdentifier, Self.deniedBundleIDs.contains(bundleID) { return }
        let appName = source?.localizedName ?? ""

        if let content = pasteboard.string(forType: .string),
           !content.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            captureText(content, app: appName)
        } else if let image = imageOnPasteboard() {
            captureImage(image, app: appName)
        } else if let urls = fileURLsOnPasteboard() {
            captureFiles(urls, app: appName)
        }
    }

    // MARK: - Text

    private func captureText(_ content: String, app appName: String) {
        if content == ignoredContent { ignoredContent = nil; return }
        if content == lastContent { return }
        lastContent = content

        // /cpy copies through the shell helper, which puts the text on the
        // clipboard first and writes its own history entry (with a label worth
        // keeping) a moment later. Whichever of us polls first would otherwise
        // log a second, unlabelled copy of the same clip — so pause, then look.
        DispatchQueue.main.asyncAfter(deadline: .now() + Self.cliGracePeriod) { [weak self] in
            guard let self, !self.isPaused, !self.wasJustLoggedByCLI(content) else { return }
            if let record = try? self.store.append(content: content, app: appName) {
                self.onCapture?(record)
            }
        }
    }

    /// Long enough for the helper to finish writing its entry, short enough
    /// that the clip is in the picker before you can open it.
    private static let cliGracePeriod: TimeInterval = 0.6

    // MARK: - Images

    /// PNG if the app offered it, otherwise whatever it did offer, re-encoded.
    /// Screenshots arrive as PNG; Preview and design tools tend to send TIFF,
    /// which is many times larger for the same picture.
    private func imageOnPasteboard() -> (data: Data, width: Int, height: Int)? {
        let png = NSPasteboard.PasteboardType("public.png")
        if let data = pasteboard.data(forType: png), let rep = NSBitmapImageRep(data: data) {
            return (data, rep.pixelsWide, rep.pixelsHigh)
        }
        guard let tiff = pasteboard.data(forType: .tiff),
              let rep = NSBitmapImageRep(data: tiff),
              let converted = rep.representation(using: .png, properties: [:])
        else { return nil }
        return (converted, rep.pixelsWide, rep.pixelsHigh)
    }

    private func captureImage(_ image: (data: Data, width: Int, height: Int), app appName: String) {
        let digest = SHA256.hash(data: image.data).map { String(format: "%02x", $0) }.joined()
        if digest == ignoredDigest { ignoredDigest = nil; return }
        if digest == lastDigest { return }
        lastDigest = digest

        let size = ByteCountFormatter.string(fromByteCount: Int64(image.data.count), countStyle: .file)
        let summary = "image \(image.width)×\(image.height) · \(size)"
        let store = self.store

        // OCR takes a few hundred ms on a full-screen capture — far too long for
        // the main thread, which is also drawing the picker. Skip it for images
        // too big to keep anyway.
        ocrQueue.async { [weak self] in
            let text = image.data.count <= store.maxBinaryBytes
                ? TextRecognizer.text(in: image.data) : ""
            let preview = text.isEmpty ? summary : "\(summary) · \(text)"
            let record = try? store.append(data: image.data, fileExtension: "png", type: "image",
                                           preview: ClipRecord.makePreview(preview),
                                           app: appName, ocr: text)
            Log.debug("image captured: \(summary), \(text.count) chars of text")
            if let record { DispatchQueue.main.async { self?.onCapture?(record) } }
        }
    }

    private let ocrQueue = DispatchQueue(label: "io.hammant.smartclip.ocr", qos: .utility)

    // MARK: - Files

    private func fileURLsOnPasteboard() -> [URL]? {
        let urls = pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL]
        guard let urls, !urls.isEmpty, urls.allSatisfy(\.isFileURL) else { return nil }
        return urls
    }

    /// Only the paths are stored, never the files themselves — copying a 4 GB
    /// video in the Finder costs a few dozen bytes of history.
    private func captureFiles(_ urls: [URL], app appName: String) {
        let paths = urls.map(\.path).joined(separator: "\n")
        if paths == lastContent { return }
        lastContent = paths

        let names = urls.prefix(3).map { $0.lastPathComponent }.joined(separator: ", ")
        let suffix = urls.count > 3 ? ", +\(urls.count - 3) more" : ""
        let preview = "\(urls.count) file\(urls.count == 1 ? "" : "s") · \(names)\(suffix)"
        if let record = try? store.append(content: paths, type: "files", label: preview, app: appName) {
            onCapture?(record)
        }
    }

    /// Some apps declare who they are on the pasteboard; otherwise whatever is
    /// in front when the copy lands is right in practice.
    private func sourceApplication() -> NSRunningApplication? {
        if let id = pasteboard.string(forType: NSPasteboard.PasteboardType("org.nspasteboard.source")),
           let match = NSRunningApplication.runningApplications(withBundleIdentifier: id).first {
            return match
        }
        let frontmost = NSWorkspace.shared.frontmostApplication
        if frontmost?.bundleIdentifier == Bundle.main.bundleIdentifier { return nil }
        return frontmost
    }

    /// An entry with no source app was written by the shell helper.
    private func wasJustLoggedByCLI(_ content: String) -> Bool {
        let now = Date()
        return store.recent(5).contains { record in
            guard record.app.isEmpty, let when = record.date,
                  now.timeIntervalSince(when) < 3
            else { return false }
            return store.content(of: record) == content
        }
    }
}
