import AppKit
import SmartClipCore

/// macOS never tells you the clipboard changed, so like every clipboard manager
/// this polls `NSPasteboard.general.changeCount` — an integer compare, a couple
/// of times a second, costing essentially nothing.
final class ClipboardWatcher {
    private let store: HistoryStore
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var lastContent: String?
    private var ignoredContent: String?
    private var timer: Timer?

    var isPaused = false
    var onCapture: ((ClipRecord) -> Void)?

    /// Password managers tag what they copy; nspasteboard.org's convention is
    /// that clipboard managers skip anything carrying these markers. That is far
    /// more reliable than trying to recognise a password by looking at it.
    private static let skipMarkers: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    /// Belt and braces for apps that don't set the markers.
    private static let deniedBundleIDs: Set<String> = [
        "com.1password.1password", "com.1password.1password7", "com.agilebits.onepassword7",
        "com.apple.keychainaccess", "com.bitwarden.desktop", "com.lastpass.LastPass",
        "com.dashlane.Dashlane", "in.sinew.Enpass-Desktop",
    ]

    init(store: HistoryStore) {
        self.store = store
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in self?.tick() }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    /// Called before we put something on the clipboard ourselves, so pasting
    /// from history doesn't re-record the same clip.
    func ignore(_ content: String) {
        ignoredContent = content
    }

    private func tick() {
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount
        guard !isPaused else { return }

        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.skipMarkers) else { return }

        guard let content = pasteboard.string(forType: .string),
              !content.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        else { return }

        if content == ignoredContent { ignoredContent = nil; return }
        if content == lastContent { return }

        let source = sourceApplication()
        if let bundleID = source?.bundleIdentifier, Self.deniedBundleIDs.contains(bundleID) { return }

        lastContent = content
        let appName = source?.localizedName ?? ""

        // /cpy copies through the shell helper, which puts the text on the
        // clipboard first and writes its own history entry (with a label worth
        // keeping) a moment later. Whichever of us polls first would otherwise
        // log a second, unlabelled copy of the same clip — so pause, then look.
        DispatchQueue.main.asyncAfter(deadline: .now() + Self.cliGracePeriod) { [weak self] in
            guard let self, !self.isPaused, !self.wasJustLoggedByCLI(content) else { return }
            if let record = try? self.store.append(content: content, app: appName) {
                self.onCapture?(record)
            }
        }
    }

    /// Long enough for the helper to finish writing its entry, short enough
    /// that the clip is in the picker before you can open it.
    private static let cliGracePeriod: TimeInterval = 0.6

    /// Some apps declare who they are on the pasteboard; otherwise whatever is
    /// in front when the copy lands is right in practice.
    private func sourceApplication() -> NSRunningApplication? {
        if let id = pasteboard.string(forType: NSPasteboard.PasteboardType("org.nspasteboard.source")),
           let match = NSRunningApplication.runningApplications(withBundleIdentifier: id).first {
            return match
        }
        let frontmost = NSWorkspace.shared.frontmostApplication
        if frontmost?.bundleIdentifier == Bundle.main.bundleIdentifier { return nil }
        return frontmost
    }

    /// An entry with no source app was written by the shell helper.
    private func wasJustLoggedByCLI(_ content: String) -> Bool {
        let now = Date()
        return store.recent(5).contains { record in
            guard record.app.isEmpty, let when = record.date,
                  now.timeIntervalSince(when) < 3
            else { return false }
            return store.content(of: record) == content
        }
    }
}
